# Generated by Django 6.0.2 on 2026-03-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('aisle_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('price', models.FloatField(default=100)),
            ],
        ),
    ]
